### ISSUE TITLE
Artifactory API calls in infinite loop

### ISSUE THREAD

**Issue by DominikBucko** [StageCentral/backstage-artifactory-plugin#1]
Hi, I was trying to use the plugin and I noticed that it is spamming API requests for artifactory. Upon further investigation, I noticed, that it is because of useEffect hook does not have empty dependency array specified. This causes the effect (AF call) to be executed upon every render. 

I can do a PR, as I already tested the fix locally in my instance.

**Comment by slimctl** [comment]
@antweiss any update on this?

**Comment by antweiss** [comment]
Hi @DominikBucko @ssliman , guess I totally missed this in the mess we've been through. Will look into it tomorrow.

**Comment by antweiss** [comment]
PR merged. Thanks! Version 0.1.4 of the frontend plugin released to npmjs

**Comment by antweiss** [comment]
thank you
