### ISSUE TITLE
Allow anonymous Artifactory authentication

### ISSUE THREAD

**Issue by daneah** [StageCentral/backstage-artifactory-plugin#3]
Some Artifactory instances are set up for completely anonymous access, e.g. when inside a company firewall. Currently the plugin doesn't allow for an empty username and password, or for those fields to be omitted altogether.

**Comment by daneah** [comment]
Hmm, it's possible Artifactory doesn't allow anonymous AQL usage in general, which is perhaps good security practice if AQL can perform destructive operations. Feel free to keep or close this based on your understanding of the situation.

**Comment by antweiss** [comment]
hi, thanks for reporting this. I agree about this not being an endorsed security practice. closing
